// Pour ajouter des questions : copier un bloc existant, changer l'id, difficulty (1/2/3), category, question et answer.
const QUESTIONS = [

  // ─── FACILE — 1 gorgée ────────────────────────────────────────────────────
  { id: 1,  difficulty: 1, category: "Géographie",  question: "Quelle est la capitale de la France ?",                                            answer: "Paris" },
  { id: 2,  difficulty: 1, category: "Cinéma",       question: "Dans quel film trouve-t-on le personnage de Simba ?",                              answer: "Le Roi Lion" },
  { id: 3,  difficulty: 1, category: "Science",      question: "Combien de pattes a une araignée ?",                                              answer: "8" },
  { id: 4,  difficulty: 1, category: "Art",          question: "Qui a peint la Joconde ?",                                                        answer: "Léonard de Vinci" },
  { id: 5,  difficulty: 1, category: "Science",      question: "Quelle est la planète la plus proche du Soleil ?",                                answer: "Mercure" },
  { id: 6,  difficulty: 1, category: "Sport",        question: "Quel sport se joue à Wimbledon ?",                                               answer: "Le tennis" },
  { id: 7,  difficulty: 1, category: "Sport",        question: "Combien de joueurs composent une équipe de football sur le terrain ?",            answer: "11" },
  { id: 8,  difficulty: 1, category: "Géographie",  question: "Dans quelle ville se trouve la Tour Eiffel ?",                                    answer: "Paris" },
  { id: 9,  difficulty: 1, category: "Littérature", question: "Quel est le nom du sorcier principal de la saga Harry Potter ?",                  answer: "Harry Potter" },
  { id: 10, difficulty: 1, category: "Musique",     question: "Combien de cordes a une guitare classique ?",                                     answer: "6" },
  { id: 11, difficulty: 1, category: "Nourriture",  question: "Quel est l'ingrédient principal du guacamole ?",                                  answer: "L'avocat" },
  { id: 12, difficulty: 1, category: "Musique",     question: "Dans quel pays est né Mozart ?",                                                   answer: "Autriche" },
  { id: 13, difficulty: 1, category: "BD",           question: "Quel est le nom du chien de Tintin ?",                                           answer: "Milou" },
  { id: 14, difficulty: 1, category: "Maths",       question: "Combien de côtés a un hexagone ?",                                                answer: "6" },
  { id: 15, difficulty: 1, category: "Géographie",  question: "Quelle est la capitale de l'Espagne ?",                                           answer: "Madrid" },
  { id: 16, difficulty: 1, category: "Science",     question: "Quel est l'animal le plus grand du monde ?",                                      answer: "La baleine bleue" },
  { id: 17, difficulty: 1, category: "Cinéma",      question: "Dans quel pays se trouve Hollywood ?",                                            answer: "Les États-Unis" },
  { id: 18, difficulty: 1, category: "Cinéma",      question: "Qui joue le rôle de Jack dans le film Titanic (1997) ?",                         answer: "Leonardo DiCaprio" },
  { id: 19, difficulty: 1, category: "Géographie",  question: "Quelle est la capitale du Portugal ?",                                            answer: "Lisbonne" },
  { id: 20, difficulty: 1, category: "Culture Pop", question: "Quel est le surnom de la ville de New York ?",                                    answer: "La Grosse Pomme (The Big Apple)" },
  { id: 21, difficulty: 1, category: "Nourriture",  question: "Quelle boisson alcoolisée est faite à partir de raisins fermentés ?",             answer: "Le vin" },
  { id: 22, difficulty: 1, category: "Cinéma",      question: "Quel personnage Disney vit dans un château enchanté avec des chandeliers parlants ?", answer: "La Belle (La Belle et la Bête)" },
  { id: 23, difficulty: 1, category: "Géographie",  question: "Sur quel continent se trouve l'Égypte ?",                                        answer: "L'Afrique" },
  { id: 24, difficulty: 1, category: "Science",     question: "Combien de planètes y a-t-il dans notre système solaire ?",                       answer: "8" },

  // ─── MOYEN — 2 gorgées ────────────────────────────────────────────────────
  { id: 25, difficulty: 2, category: "Histoire",    question: "En quelle année a eu lieu la Révolution française ?",                             answer: "1789" },
  { id: 26, difficulty: 2, category: "Géographie",  question: "Quelle est la capitale de l'Australie ?",                                        answer: "Canberra" },
  { id: 27, difficulty: 2, category: "Musique",     question: "Qui a composé la célèbre 5ème Symphonie ?",                                      answer: "Beethoven" },
  { id: 28, difficulty: 2, category: "Cinéma",      question: "Dans quel film Marlon Brando joue-t-il le rôle du Parrain ?",                    answer: "Le Parrain" },
  { id: 29, difficulty: 2, category: "Science",     question: "Quelle est la formule chimique de l'eau ?",                                      answer: "H₂O" },
  { id: 30, difficulty: 2, category: "Géographie",  question: "Quel est le pays le plus peuplé du monde (depuis 2023) ?",                       answer: "L'Inde" },
  { id: 31, difficulty: 2, category: "Sport",       question: "Dans quel sport utilise-t-on un volant ?",                                       answer: "Le badminton" },
  { id: 32, difficulty: 2, category: "Littérature", question: "Qui a écrit 'Les Misérables' ?",                                                 answer: "Victor Hugo" },
  { id: 33, difficulty: 2, category: "Géographie",  question: "Quelle est la monnaie du Japon ?",                                               answer: "Le yen" },
  { id: 34, difficulty: 2, category: "Histoire",    question: "En quelle année l'homme a-t-il marché sur la Lune pour la première fois ?",      answer: "1969" },
  { id: 35, difficulty: 2, category: "Sport",       question: "Quel pays a remporté la Coupe du monde de football en 2018 ?",                   answer: "La France" },
  { id: 36, difficulty: 2, category: "Tech",        question: "Qui est le créateur de Facebook ?",                                              answer: "Mark Zuckerberg" },
  { id: 37, difficulty: 2, category: "Géographie",  question: "Dans quel pays se trouve le Colisée ?",                                          answer: "Italie (Rome)" },
  { id: 38, difficulty: 2, category: "Cinéma",      question: "Quel acteur joue le rôle d'Iron Man dans l'univers Marvel ?",                    answer: "Robert Downey Jr." },
  { id: 39, difficulty: 2, category: "Géographie",  question: "Combien de pays composent l'Union Européenne ?",                                 answer: "27" },
  { id: 40, difficulty: 2, category: "Géographie",  question: "Quelle est la montagne la plus haute du monde ?",                                answer: "L'Everest" },
  { id: 41, difficulty: 2, category: "Littérature", question: "Qui a écrit 'L'Étranger' ?",                                                    answer: "Albert Camus" },
  { id: 42, difficulty: 2, category: "Histoire",    question: "Quel est le vrai prénom de Voltaire ?",                                          answer: "François-Marie Arouet" },
  { id: 43, difficulty: 2, category: "Géographie",  question: "Dans quel pays se trouve l'Acropole d'Athènes ?",                               answer: "La Grèce" },
  { id: 44, difficulty: 2, category: "Nourriture",  question: "Quel pays est le plus grand producteur de bière au monde ?",                     answer: "La Chine" },
  { id: 45, difficulty: 2, category: "Science",     question: "Combien de chromosomes a un être humain ?",                                      answer: "46 (23 paires)" },
  { id: 46, difficulty: 2, category: "Cinéma",      question: "Dans quelle saga trouve-t-on le personnage de 'Gollum' ?",                       answer: "Le Seigneur des Anneaux" },
  { id: 47, difficulty: 2, category: "Musique",     question: "Quel groupe a sorti l'album 'Thriller' en 1982 ?",                              answer: "Michael Jackson (ce n'est pas un groupe, c'est Michael Jackson)" },
  { id: 48, difficulty: 2, category: "Géographie",  question: "Quelle est la plus grande île du monde ?",                                       answer: "Le Groenland" },

  // ─── DIFFICILE — 3 gorgées ────────────────────────────────────────────────
  { id: 49, difficulty: 3, category: "Géographie",  question: "Quelle est la capitale de la Mongolie ?",                                        answer: "Oulan-Bator" },
  { id: 50, difficulty: 3, category: "Histoire",    question: "En quelle année est mort Napoléon Bonaparte ?",                                  answer: "1821" },
  { id: 51, difficulty: 3, category: "Art",         question: "Qui a peint 'La Nuit étoilée' ?",                                               answer: "Vincent van Gogh" },
  { id: 52, difficulty: 3, category: "Science",     question: "Quel est l'élément chimique de symbole 'Au' ?",                                 answer: "L'or" },
  { id: 53, difficulty: 3, category: "Géographie",  question: "Quelle est la plus longue rivière d'Afrique ?",                                 answer: "Le Nil" },
  { id: 54, difficulty: 3, category: "Littérature", question: "Qui a écrit 'À la recherche du temps perdu' ?",                                 answer: "Marcel Proust" },
  { id: 55, difficulty: 3, category: "Histoire",    question: "En quelle année le Mur de Berlin est-il tombé ?",                               answer: "1989" },
  { id: 56, difficulty: 3, category: "Sport",       question: "Quel pays a remporté le plus de Coupes du monde de football ? Combien ?",       answer: "Le Brésil — 5 fois" },
  { id: 57, difficulty: 3, category: "Géographie",  question: "Quelle est la capitale des Philippines ?",                                       answer: "Manille" },
  { id: 58, difficulty: 3, category: "Histoire",    question: "Qui a inventé la dynamite ?",                                                    answer: "Alfred Nobel" },
  { id: 59, difficulty: 3, category: "Histoire",    question: "Quel est le nom du premier satellite artificiel lancé dans l'espace ?",          answer: "Spoutnik" },
  { id: 60, difficulty: 3, category: "Littérature", question: "Dans quel roman trouve-t-on le personnage de Holden Caulfield ?",               answer: "L'Attrape-cœurs (J.D. Salinger)" },
  { id: 61, difficulty: 3, category: "Musique",     question: "Combien de symphonies Beethoven a-t-il composées ?",                            answer: "9" },
  { id: 62, difficulty: 3, category: "Géographie",  question: "Quel est le pays le plus petit du monde ?",                                     answer: "Le Vatican" },
  { id: 63, difficulty: 3, category: "Histoire",    question: "En quelle année la Joconde a-t-elle été volée au Louvre ?",                     answer: "1911" },
  { id: 64, difficulty: 3, category: "Science",     question: "Quel est le symbole chimique du mercure ?",                                     answer: "Hg" },
  { id: 65, difficulty: 3, category: "Art",         question: "Qui a peint le plafond de la Chapelle Sixtine ?",                               answer: "Michel-Ange" },
  { id: 66, difficulty: 3, category: "Géographie",  question: "Quelle est la capitale de la Nouvelle-Zélande ?",                              answer: "Wellington" },
  { id: 67, difficulty: 3, category: "Littérature", question: "Qui est l'auteur de 'Don Quichotte' ?",                                        answer: "Miguel de Cervantes" },
  { id: 68, difficulty: 3, category: "Histoire",    question: "En quelle année la Tour Eiffel a-t-elle été inaugurée ?",                       answer: "1889" },
  { id: 69, difficulty: 3, category: "Science",     question: "Quelle est la vitesse de la lumière (en km/s, arrondie) ?",                     answer: "300 000 km/s" },
  { id: 70, difficulty: 3, category: "Nourriture",  question: "Quel champignon est le plus cher au monde au kilo ?",                           answer: "La truffe blanche d'Alba" },
  { id: 71, difficulty: 3, category: "Musique",     question: "Quel groupe a vendu le plus de disques dans l'histoire de la musique ?",        answer: "Les Beatles" },
  { id: 72, difficulty: 3, category: "Géographie",  question: "Quel est le désert le plus froid du monde ?",                                  answer: "L'Antarctique" },
];
