// Pour ajouter des questions : copier un bloc existant, changer l'id, difficulty (1/2/3), category, question et answer.
const QUESTIONS = [

  // ─── FACILE — 1 gorgée ────────────────────────────────────────────────────
  { id: 1,   difficulty: 1, category: "Géographie",  question: "Quelle est la capitale de la France ?",                                                         answer: "Paris" },
  { id: 2,   difficulty: 1, category: "Cinéma",      question: "Dans quel film trouve-t-on le personnage de Simba ?",                                            answer: "Le Roi Lion" },
  { id: 3,   difficulty: 1, category: "Science",     question: "Combien de pattes a une araignée ?",                                                             answer: "8" },
  { id: 4,   difficulty: 1, category: "Art",         question: "Qui a peint la Joconde ?",                                                                       answer: "Léonard de Vinci" },
  { id: 5,   difficulty: 1, category: "Science",     question: "Quelle est la planète la plus proche du Soleil ?",                                               answer: "Mercure" },
  { id: 6,   difficulty: 1, category: "Sport",       question: "Quel sport se joue à Wimbledon ?",                                                               answer: "Le tennis" },
  { id: 7,   difficulty: 1, category: "Sport",       question: "Combien de joueurs composent une équipe de football sur le terrain ?",                           answer: "11" },
  { id: 8,   difficulty: 1, category: "Géographie",  question: "Dans quelle ville se trouve la Tour Eiffel ?",                                                   answer: "Paris" },
  { id: 9,   difficulty: 1, category: "Littérature", question: "Quel est le nom du sorcier principal de la saga Harry Potter ?",                                 answer: "Harry Potter" },
  { id: 10,  difficulty: 1, category: "Musique",     question: "Combien de cordes a une guitare classique ?",                                                    answer: "6" },
  { id: 11,  difficulty: 1, category: "Nourriture",  question: "Quel est l'ingrédient principal du guacamole ?",                                                 answer: "L'avocat" },
  { id: 12,  difficulty: 1, category: "Musique",     question: "Dans quel pays est né Mozart ?",                                                                  answer: "Autriche" },
  { id: 13,  difficulty: 1, category: "BD",          question: "Quel est le nom du chien de Tintin ?",                                                           answer: "Milou" },
  { id: 14,  difficulty: 1, category: "Maths",       question: "Combien de côtés a un hexagone ?",                                                               answer: "6" },
  { id: 15,  difficulty: 1, category: "Géographie",  question: "Quelle est la capitale de l'Espagne ?",                                                          answer: "Madrid" },
  { id: 16,  difficulty: 1, category: "Science",     question: "Quel est l'animal le plus grand du monde ?",                                                     answer: "La baleine bleue" },
  { id: 17,  difficulty: 1, category: "Cinéma",      question: "Dans quel pays se trouve Hollywood ?",                                                           answer: "Les États-Unis" },
  { id: 18,  difficulty: 1, category: "Cinéma",      question: "Qui joue le rôle de Jack dans le film Titanic (1997) ?",                                        answer: "Leonardo DiCaprio" },
  { id: 19,  difficulty: 1, category: "Géographie",  question: "Quelle est la capitale du Portugal ?",                                                           answer: "Lisbonne" },
  { id: 20,  difficulty: 1, category: "Culture Pop", question: "Quel est le surnom de la ville de New York ?",                                                   answer: "La Grosse Pomme (The Big Apple)" },
  { id: 21,  difficulty: 1, category: "Nourriture",  question: "Quelle boisson alcoolisée est faite à partir de raisins fermentés ?",                           answer: "Le vin" },
  { id: 22,  difficulty: 1, category: "Cinéma",      question: "Quel personnage Disney vit dans un château enchanté avec des chandeliers parlants ?",            answer: "La Belle (La Belle et la Bête)" },
  { id: 23,  difficulty: 1, category: "Géographie",  question: "Sur quel continent se trouve l'Égypte ?",                                                       answer: "L'Afrique" },
  { id: 24,  difficulty: 1, category: "Science",     question: "Combien de planètes y a-t-il dans notre système solaire ?",                                     answer: "8" },
  { id: 25,  difficulty: 1, category: "Géographie",  question: "Quelle est la capitale de l'Italie ?",                                                          answer: "Rome" },
  { id: 26,  difficulty: 1, category: "Géographie",  question: "Quelle est la capitale de l'Allemagne ?",                                                       answer: "Berlin" },
  { id: 27,  difficulty: 1, category: "Géographie",  question: "Quel est le plus grand océan du monde ?",                                                       answer: "L'océan Pacifique" },
  { id: 28,  difficulty: 1, category: "Science",     question: "Quel est le gaz le plus présent dans l'air que l'on respire ?",                                 answer: "L'azote" },
  { id: 29,  difficulty: 1, category: "Animaux",     question: "Quel est l'animal le plus rapide sur terre ?",                                                   answer: "Le guépard" },
  { id: 30,  difficulty: 1, category: "Nourriture",  question: "De quel pays est originaire la pizza ?",                                                         answer: "L'Italie" },
  { id: 31,  difficulty: 1, category: "Musique",     question: "Qui est surnommé le \"Roi du Rock\" ?",                                                         answer: "Elvis Presley" },
  { id: 32,  difficulty: 1, category: "Cinéma",      question: "Quel personnage dit \"Que la Force soit avec toi\" ?",                                          answer: "Des personnages de Star Wars" },
  { id: 33,  difficulty: 1, category: "Maths",       question: "Combien font 7 × 8 ?",                                                                          answer: "56" },
  { id: 34,  difficulty: 1, category: "Géographie",  question: "Quel fleuve traverse Paris ?",                                                                   answer: "La Seine" },
  { id: 35,  difficulty: 1, category: "Littérature", question: "Qui est l'auteur des Fables (\"La Cigale et la Fourmi\") ?",                                   answer: "Jean de La Fontaine" },
  { id: 36,  difficulty: 1, category: "Science",     question: "Quelle planète est surnommée la planète rouge ?",                                               answer: "Mars" },
  { id: 37,  difficulty: 1, category: "Animaux",     question: "Combien de pattes a un insecte ?",                                                               answer: "6" },
  { id: 38,  difficulty: 1, category: "Géographie",  question: "Quelle est la capitale du Royaume-Uni ?",                                                       answer: "Londres" },
  { id: 39,  difficulty: 1, category: "Nourriture",  question: "Quel légume orange est riche en bêta-carotène ?",                                               answer: "La carotte" },
  { id: 40,  difficulty: 1, category: "Cinéma",      question: "Quel studio a créé le personnage de Mickey Mouse ?",                                            answer: "Disney" },
  { id: 41,  difficulty: 1, category: "Maths",       question: "Combien de secondes y a-t-il dans une minute ?",                                                answer: "60" },
  { id: 42,  difficulty: 1, category: "Sport",       question: "Combien de joueurs composent une équipe de basketball sur le terrain ?",                         answer: "5" },
  { id: 43,  difficulty: 1, category: "Histoire",    question: "Qui était le premier président des États-Unis ?",                                               answer: "George Washington" },
  { id: 44,  difficulty: 1, category: "Musique",     question: "Quelle pop star est surnommée \"Queen of Pop\" ?",                                              answer: "Madonna" },
  { id: 45,  difficulty: 1, category: "Animaux",     question: "Quel est l'animal symbole de l'Australie ?",                                                    answer: "Le kangourou" },
  { id: 46,  difficulty: 1, category: "Tech",        question: "Quelle entreprise fabrique l'iPhone ?",                                                          answer: "Apple" },
  { id: 47,  difficulty: 1, category: "Cinéma",      question: "Dans quel film Pixar des jouets prennent-ils vie ?",                                            answer: "Toy Story" },
  { id: 48,  difficulty: 1, category: "Nourriture",  question: "Quelle boisson chaude est la plus consommée dans le monde ?",                                   answer: "Le thé" },
  { id: 49,  difficulty: 1, category: "Science",     question: "Combien d'os a le corps humain adulte ?",                                                       answer: "206" },
  { id: 50,  difficulty: 1, category: "Littérature", question: "Qui a écrit \"Le Petit Prince\" ?",                                                             answer: "Antoine de Saint-Exupéry" },
  { id: 51,  difficulty: 1, category: "Animaux",     question: "Quel mammifère pond des œufs ?",                                                                answer: "L'ornithorynque" },
  { id: 52,  difficulty: 1, category: "Musique",     question: "Qui chante \"Bohemian Rhapsody\" ?",                                                            answer: "Queen" },
  { id: 53,  difficulty: 1, category: "Tech",        question: "Que signifie \"WWW\" ?",                                                                        answer: "World Wide Web" },
  { id: 54,  difficulty: 1, category: "Cinéma",      question: "Qui joue Hermione Granger dans la saga Harry Potter ?",                                         answer: "Emma Watson" },
  { id: 55,  difficulty: 1, category: "Animaux",     question: "Quel oiseau sait nager mais ne peut pas voler ?",                                               answer: "Le manchot (pingouin)" },
  { id: 56,  difficulty: 1, category: "Littérature", question: "Qui a créé le personnage de Sherlock Holmes ?",                                                 answer: "Arthur Conan Doyle" },
  { id: 57,  difficulty: 1, category: "Sport",       question: "Combien de points vaut un essai au rugby à XV ?",                                               answer: "5" },
  { id: 58,  difficulty: 1, category: "Cinéma",      question: "Qui a réalisé \"Inception\" ?",                                                                 answer: "Christopher Nolan" },
  { id: 59,  difficulty: 1, category: "Géographie",  question: "Quelle est la capitale du Brésil ?",                                                            answer: "Brasilia" },
  { id: 60,  difficulty: 1, category: "Culture Pop", question: "Dans quelle série animée voit-on la famille Simpson ?",                                         answer: "Les Simpson" },
  { id: 61,  difficulty: 1, category: "Science",     question: "Quel organe pompe le sang dans le corps humain ?",                                              answer: "Le cœur" },
  { id: 62,  difficulty: 1, category: "Sport",       question: "Dans quel sport utilise-t-on des \"clubs\" ?",                                                  answer: "Le golf" },
  { id: 63,  difficulty: 1, category: "Géographie",  question: "Quelle est la capitale du Mexique ?",                                                           answer: "Mexico" },
  { id: 64,  difficulty: 1, category: "Géographie",  question: "Dans quel pays se trouve Amsterdam ?",                                                          answer: "Les Pays-Bas" },
  { id: 65,  difficulty: 1, category: "Sport",       question: "Quel sport se pratique dans un ring ?",                                                          answer: "La boxe" },
  { id: 66,  difficulty: 1, category: "Musique",     question: "Dans quel pays est né Justin Bieber ?",                                                          answer: "Le Canada" },
  { id: 67,  difficulty: 1, category: "Géographie",  question: "Quelle est la capitale de la Russie ?",                                                         answer: "Moscou" },
  { id: 68,  difficulty: 1, category: "Littérature", question: "Qui a écrit \"Roméo et Juliette\" ?",                                                          answer: "William Shakespeare" },
  { id: 69,  difficulty: 1, category: "Cinéma",      question: "Dans quel film Robin Williams joue-t-il le génie d'une lampe magique ?",                       answer: "Aladdin" },
  { id: 70,  difficulty: 1, category: "Géographie",  question: "Quelle est la capitale du Canada ?",                                                            answer: "Ottawa" },
  { id: 71,  difficulty: 1, category: "Nourriture",  question: "Quelle boisson est associée à l'Irlande ?",                                                     answer: "La Guinness" },
  { id: 72,  difficulty: 1, category: "Cinéma",      question: "Quelle actrice joue Black Widow dans les films Marvel ?",                                       answer: "Scarlett Johansson" },
  { id: 73,  difficulty: 1, category: "Science",     question: "Quelle est la température d'ébullition de l'eau à pression normale ?",                          answer: "100°C" },
  { id: 74,  difficulty: 1, category: "BD",          question: "Qui est le compagnon de Lucky Luke ?",                                                          answer: "Jolly Jumper (son cheval)" },
  { id: 75,  difficulty: 1, category: "Musique",     question: "Quel est le prénom de la chanteuse Beyoncé ?",                                                  answer: "Beyoncé" },
  { id: 76,  difficulty: 1, category: "Maths",       question: "Quelle est la forme géométrique avec 3 côtés ?",                                                answer: "Le triangle" },
  { id: 77,  difficulty: 1, category: "Histoire",    question: "Qui était Cléopâtre ?",                                                                         answer: "Reine d'Égypte" },
  { id: 78,  difficulty: 1, category: "Nourriture",  question: "Quelle épice rouge est souvent utilisée pour donner de la couleur ?",                           answer: "Le paprika" },
  { id: 79,  difficulty: 1, category: "Tech",        question: "Quel est le nom de l'assistant vocal d'Apple ?",                                                answer: "Siri" },
  { id: 80,  difficulty: 1, category: "Animaux",     question: "Quel animal est connu pour son long cou ?",                                                     answer: "La girafe" },
  { id: 81,  difficulty: 1, category: "Cinéma",      question: "Quel film d'animation Disney raconte l'histoire d'une petite sirène ?",                         answer: "La Petite Sirène" },
  { id: 82,  difficulty: 1, category: "Géographie",  question: "Quel est le plus grand continent du monde ?",                                                   answer: "L'Asie" },
  { id: 83,  difficulty: 1, category: "Sport",       question: "En quelle année ont eu lieu les Jeux Olympiques de Paris ?",                                    answer: "2024" },
  { id: 84,  difficulty: 1, category: "Musique",     question: "Combien de musiciens composent un duo ?",                                                       answer: "2" },
  { id: 85,  difficulty: 1, category: "Littérature", question: "Dans quel roman de Jules Verne un homme fait-il le tour du monde en 80 jours ?",                answer: "Le Tour du monde en quatre-vingts jours" },
  { id: 86,  difficulty: 1, category: "Science",     question: "De quelle couleur est le ciel par beau temps ?",                                                answer: "Bleu" },
  { id: 87,  difficulty: 1, category: "Géographie",  question: "Quel est le pays le plus grand d'Amérique du Sud ?",                                           answer: "Le Brésil" },
  { id: 88,  difficulty: 1, category: "Nourriture",  question: "Quelle boisson est fabriquée à partir d'orge maltée et de houblon ?",                          answer: "La bière" },
  { id: 89,  difficulty: 1, category: "Culture Pop", question: "Quel personnage de jeu vidéo est un plombier qui saute sur des champignons ?",                  answer: "Mario" },
  { id: 90,  difficulty: 1, category: "Animaux",     question: "Quel est le plus grand félin du monde ?",                                                       answer: "Le tigre" },
  { id: 91,  difficulty: 1, category: "Cinéma",      question: "Quel film raconte l'histoire du naufrage du Titanic (1997) ?",                                  answer: "Titanic" },
  { id: 92,  difficulty: 1, category: "Géographie",  question: "Dans quel pays se trouve le mont Fuji ?",                                                       answer: "Le Japon" },
  { id: 93,  difficulty: 1, category: "Musique",     question: "Quel groupe britannique est formé de John, Paul, George et Ringo ?",                            answer: "Les Beatles" },
  { id: 94,  difficulty: 1, category: "Sport",       question: "Combien de joueurs y a-t-il dans une équipe de volleyball ?",                                   answer: "6" },
  { id: 95,  difficulty: 1, category: "Maths",       question: "Combien font 100 divisé par 4 ?",                                                               answer: "25" },
  { id: 96,  difficulty: 1, category: "Histoire",    question: "Quel est le monument symbole de la liberté offert par la France aux États-Unis ?",              answer: "La Statue de la Liberté" },
  { id: 97,  difficulty: 1, category: "Nourriture",  question: "Quelle est la principale épice du café ?",                                                      answer: "Le café (c'est lui-même une graine)" },
  { id: 98,  difficulty: 1, category: "Animaux",     question: "Quel est le plus grand primate du monde ?",                                                     answer: "Le gorille" },
  { id: 99,  difficulty: 1, category: "Cinéma",      question: "Dans quelle saga voit-on des wizards, des hobbits et des elfes ?",                              answer: "Le Seigneur des Anneaux" },
  { id: 100, difficulty: 1, category: "Géographie",  question: "Quel est le plus long fleuve du monde ?",                                                       answer: "Le Nil (ou l'Amazone selon les mesures)" },

  // ─── MOYEN — 2 gorgées ────────────────────────────────────────────────────
  { id: 101, difficulty: 2, category: "Histoire",    question: "En quelle année a eu lieu la Révolution française ?",                                           answer: "1789" },
  { id: 102, difficulty: 2, category: "Géographie",  question: "Quelle est la capitale de l'Australie ?",                                                       answer: "Canberra" },
  { id: 103, difficulty: 2, category: "Musique",     question: "Qui a composé la célèbre 5ème Symphonie ?",                                                     answer: "Beethoven" },
  { id: 104, difficulty: 2, category: "Cinéma",      question: "Dans quel film Marlon Brando joue-t-il le rôle du Parrain ?",                                   answer: "Le Parrain" },
  { id: 105, difficulty: 2, category: "Science",     question: "Quelle est la formule chimique de l'eau ?",                                                     answer: "H₂O" },
  { id: 106, difficulty: 2, category: "Géographie",  question: "Quel est le pays le plus peuplé du monde depuis 2023 ?",                                        answer: "L'Inde" },
  { id: 107, difficulty: 2, category: "Sport",       question: "Dans quel sport utilise-t-on un volant ?",                                                      answer: "Le badminton" },
  { id: 108, difficulty: 2, category: "Littérature", question: "Qui a écrit \"Les Misérables\" ?",                                                              answer: "Victor Hugo" },
  { id: 109, difficulty: 2, category: "Géographie",  question: "Quelle est la monnaie du Japon ?",                                                              answer: "Le yen" },
  { id: 110, difficulty: 2, category: "Histoire",    question: "En quelle année l'homme a-t-il marché sur la Lune pour la première fois ?",                    answer: "1969" },
  { id: 111, difficulty: 2, category: "Sport",       question: "Quel pays a remporté la Coupe du monde de football en 2018 ?",                                  answer: "La France" },
  { id: 112, difficulty: 2, category: "Tech",        question: "Qui est le créateur de Facebook ?",                                                             answer: "Mark Zuckerberg" },
  { id: 113, difficulty: 2, category: "Géographie",  question: "Dans quel pays se trouve le Colisée ?",                                                         answer: "Italie (Rome)" },
  { id: 114, difficulty: 2, category: "Cinéma",      question: "Quel acteur joue le rôle d'Iron Man dans l'univers Marvel ?",                                   answer: "Robert Downey Jr." },
  { id: 115, difficulty: 2, category: "Géographie",  question: "Combien de pays composent l'Union Européenne ?",                                                answer: "27" },
  { id: 116, difficulty: 2, category: "Géographie",  question: "Quelle est la montagne la plus haute du monde ?",                                               answer: "L'Everest" },
  { id: 117, difficulty: 2, category: "Littérature", question: "Qui a écrit \"L'Étranger\" ?",                                                                 answer: "Albert Camus" },
  { id: 118, difficulty: 2, category: "Histoire",    question: "Quel est le vrai prénom de Voltaire ?",                                                         answer: "François-Marie Arouet" },
  { id: 119, difficulty: 2, category: "Géographie",  question: "Dans quel pays se trouve l'Acropole d'Athènes ?",                                              answer: "La Grèce" },
  { id: 120, difficulty: 2, category: "Nourriture",  question: "Quel pays est le plus grand producteur de bière au monde ?",                                    answer: "La Chine" },
  { id: 121, difficulty: 2, category: "Science",     question: "Combien de chromosomes a un être humain ?",                                                     answer: "46 (23 paires)" },
  { id: 122, difficulty: 2, category: "Cinéma",      question: "Dans quelle saga trouve-t-on le personnage de Gollum ?",                                        answer: "Le Seigneur des Anneaux" },
  { id: 123, difficulty: 2, category: "Musique",     question: "Qui a sorti l'album \"Thriller\" en 1982 ?",                                                   answer: "Michael Jackson" },
  { id: 124, difficulty: 2, category: "Géographie",  question: "Quelle est la plus grande île du monde ?",                                                      answer: "Le Groenland" },
  { id: 125, difficulty: 2, category: "Histoire",    question: "Quel roi de France avait le surnom de \"Roi Soleil\" ?",                                       answer: "Louis XIV" },
  { id: 126, difficulty: 2, category: "Géographie",  question: "Quel détroit sépare l'Europe de l'Afrique ?",                                                  answer: "Le détroit de Gibraltar" },
  { id: 127, difficulty: 2, category: "Science",     question: "Quel est l'organe le plus grand du corps humain ?",                                             answer: "La peau" },
  { id: 128, difficulty: 2, category: "Musique",     question: "Qui a composé \"Les Quatre Saisons\" ?",                                                       answer: "Antonio Vivaldi" },
  { id: 129, difficulty: 2, category: "Géographie",  question: "Quelle est la capitale de l'Argentine ?",                                                      answer: "Buenos Aires" },
  { id: 130, difficulty: 2, category: "Histoire",    question: "En quelle année a commencé la Première Guerre Mondiale ?",                                     answer: "1914" },
  { id: 131, difficulty: 2, category: "Science",     question: "Combien de dents a un adulte avec toutes ses dents de sagesse ?",                               answer: "32" },
  { id: 132, difficulty: 2, category: "Littérature", question: "Qui a écrit \"1984\" ?",                                                                       answer: "George Orwell" },
  { id: 133, difficulty: 2, category: "Sport",       question: "Quelle équipe a remporté le plus de Ligues des Champions de l'UEFA ?",                         answer: "Le Real Madrid" },
  { id: 134, difficulty: 2, category: "Cinéma",      question: "Qui a réalisé la trilogie \"Le Parrain\" ?",                                                   answer: "Francis Ford Coppola" },
  { id: 135, difficulty: 2, category: "Géographie",  question: "Quel est le plus grand pays du monde en superficie ?",                                         answer: "La Russie" },
  { id: 136, difficulty: 2, category: "Tech",        question: "En quelle année le premier iPhone a-t-il été présenté ?",                                      answer: "2007" },
  { id: 137, difficulty: 2, category: "Art",         question: "Quel est le musée le plus visité au monde ?",                                                   answer: "Le Louvre (Paris)" },
  { id: 138, difficulty: 2, category: "Histoire",    question: "Qui était le pharaon lors de la construction de la Grande Pyramide de Gizeh ?",                answer: "Khéops" },
  { id: 139, difficulty: 2, category: "Musique",     question: "Quel groupe de rock est surnommé \"The Fab Four\" ?",                                          answer: "Les Beatles" },
  { id: 140, difficulty: 2, category: "Science",     question: "Quel est le gaz responsable de l'effet de serre le plus connu ?",                              answer: "Le dioxyde de carbone (CO₂)" },
  { id: 141, difficulty: 2, category: "Sport",       question: "Combien de sets faut-il gagner pour remporter un match de Grand Chelem en tennis (hommes) ?",  answer: "3 (sur 5)" },
  { id: 142, difficulty: 2, category: "Littérature", question: "Qui a écrit \"Le Comte de Monte-Cristo\" ?",                                                   answer: "Alexandre Dumas" },
  { id: 143, difficulty: 2, category: "Histoire",    question: "Quel empire était gouverné par Gengis Khan ?",                                                  answer: "L'empire mongol" },
  { id: 144, difficulty: 2, category: "Nourriture",  question: "Quelle région de France est connue pour son camembert ?",                                      answer: "La Normandie" },
  { id: 145, difficulty: 2, category: "Cinéma",      question: "Quel film a popularisé la réplique \"I'll be back\" ?",                                        answer: "Terminator" },
  { id: 146, difficulty: 2, category: "Science",     question: "Quel scientifique a formulé la loi de la gravitation universelle ?",                            answer: "Isaac Newton" },
  { id: 147, difficulty: 2, category: "Géographie",  question: "Quelle est la capitale de la Turquie ?",                                                       answer: "Ankara" },
  { id: 148, difficulty: 2, category: "Sport",       question: "Quel athlète jamaïcain a battu le record du monde du 100m en 2009 ?",                          answer: "Usain Bolt" },
  { id: 149, difficulty: 2, category: "Histoire",    question: "Quel pays a envoyé le premier homme dans l'espace ?",                                           answer: "L'URSS — Youri Gagarine" },
  { id: 150, difficulty: 2, category: "Littérature", question: "Qui a écrit \"Crime et Châtiment\" ?",                                                         answer: "Fiodor Dostoïevski" },
  { id: 151, difficulty: 2, category: "Géographie",  question: "Quel pays est composé de plus de 17 000 îles ?",                                               answer: "L'Indonésie" },
  { id: 152, difficulty: 2, category: "Tech",        question: "Quel langage de programmation a été créé par Guido van Rossum ?",                               answer: "Python" },
  { id: 153, difficulty: 2, category: "Art",         question: "Qui a sculpté \"Le Penseur\" ?",                                                               answer: "Auguste Rodin" },
  { id: 154, difficulty: 2, category: "Histoire",    question: "En quelle année a été signée la Déclaration d'indépendance américaine ?",                     answer: "1776" },
  { id: 155, difficulty: 2, category: "Science",     question: "Quelle est la distance moyenne entre la Terre et la Lune ?",                                   answer: "384 400 km" },
  { id: 156, difficulty: 2, category: "Géographie",  question: "Quel est le point le plus bas à la surface de la Terre ?",                                     answer: "La mer Morte" },
  { id: 157, difficulty: 2, category: "Sport",       question: "Quel pays a remporté le plus de médailles d'or aux Jeux Olympiques d'été de tous les temps ?", answer: "Les États-Unis" },
  { id: 158, difficulty: 2, category: "Cinéma",      question: "Qui a réalisé \"2001 : L'Odyssée de l'espace\" ?",                                            answer: "Stanley Kubrick" },
  { id: 159, difficulty: 2, category: "Littérature", question: "Quel auteur a créé le personnage de Dracula ?",                                                 answer: "Bram Stoker" },
  { id: 160, difficulty: 2, category: "Musique",     question: "Quelle artiste a sorti l'album \"21\" en 2011 ?",                                              answer: "Adele" },
  { id: 161, difficulty: 2, category: "Histoire",    question: "Qui était le dernier tsar de Russie ?",                                                         answer: "Nicolas II" },
  { id: 162, difficulty: 2, category: "Tech",        question: "Quel est le nom du premier système d'exploitation créé par Microsoft ?",                       answer: "MS-DOS" },
  { id: 163, difficulty: 2, category: "Science",     question: "Quelle est la fonction de l'ADN ?",                                                            answer: "Stocker et transmettre l'information génétique" },
  { id: 164, difficulty: 2, category: "Cinéma",      question: "Quel film a rapporté le plus d'argent au box-office mondial (avant ajustement) ?",             answer: "Avatar (2009)" },
  { id: 165, difficulty: 2, category: "Sport",       question: "En quelle année ont eu lieu les premiers Jeux Olympiques d'hiver ?",                           answer: "1924 (Chamonix)" },
  { id: 166, difficulty: 2, category: "Art",         question: "Qui a peint \"Le Cri\" ?",                                                                    answer: "Edvard Munch" },
  { id: 167, difficulty: 2, category: "Géographie",  question: "Quelle est la capitale de l'Arabie Saoudite ?",                                                answer: "Riyad" },
  { id: 168, difficulty: 2, category: "Littérature", question: "Qui a écrit \"Madame Bovary\" ?",                                                              answer: "Gustave Flaubert" },
  { id: 169, difficulty: 2, category: "Musique",     question: "Quel est le vrai nom de Lady Gaga ?",                                                          answer: "Stefani Joanne Angelina Germanotta" },
  { id: 170, difficulty: 2, category: "Cinéma",      question: "Dans quel film Jodie Foster joue-t-elle un agent du FBI face à Hannibal Lecter ?",             answer: "Le Silence des agneaux" },
  { id: 171, difficulty: 2, category: "Géographie",  question: "Quel pays possède le plus grand nombre de lacs du monde ?",                                    answer: "Le Canada" },
  { id: 172, difficulty: 2, category: "Science",     question: "Quelle est la couche de l'atmosphère la plus proche de la surface terrestre ?",               answer: "La troposphère" },
  { id: 173, difficulty: 2, category: "Sport",       question: "Combien de points vaut un panier à 3 points au basket-ball ?",                                 answer: "3 points" },
  { id: 174, difficulty: 2, category: "Tech",        question: "Qui a co-fondé Apple avec Steve Jobs ?",                                                        answer: "Steve Wozniak" },
  { id: 175, difficulty: 2, category: "Art",         question: "Dans quelle ville se trouve le musée du Prado ?",                                               answer: "Madrid" },
  { id: 176, difficulty: 2, category: "Nourriture",  question: "Quelle épice donne sa couleur jaune au curry ?",                                               answer: "Le curcuma" },
  { id: 177, difficulty: 2, category: "Géographie",  question: "Quel est le plus long mur du monde ?",                                                         answer: "La Grande Muraille de Chine" },
  { id: 178, difficulty: 2, category: "Cinéma",      question: "Qui joue le rôle de James Bond dans \"Casino Royale\" (2006) ?",                               answer: "Daniel Craig" },
  { id: 179, difficulty: 2, category: "Histoire",    question: "En quelle année fut créée la Société des Nations (SDN) ?",                                    answer: "1920" },
  { id: 180, difficulty: 2, category: "Science",     question: "Quel est l'élément le plus abondant dans l'univers ?",                                         answer: "L'hydrogène" },
  { id: 181, difficulty: 2, category: "Littérature", question: "Quel auteur français a reçu le Prix Nobel de littérature en 1957 ?",                          answer: "Albert Camus" },
  { id: 182, difficulty: 2, category: "Géographie",  question: "Quel pays est surnommé \"le pays du Soleil Levant\" ?",                                       answer: "Le Japon" },
  { id: 183, difficulty: 2, category: "Sport",       question: "Quel joueur de football a remporté le plus de Ballons d'Or ?",                                 answer: "Lionel Messi (8 Ballons d'Or)" },
  { id: 184, difficulty: 2, category: "Cinéma",      question: "Quel acteur a joué le rôle de Forrest Gump ?",                                                 answer: "Tom Hanks" },
  { id: 185, difficulty: 2, category: "Art",         question: "Qui a peint \"Las Meninas\" ?",                                                               answer: "Diego Velázquez" },
  { id: 186, difficulty: 2, category: "Nourriture",  question: "Quel alcool entre dans la composition d'un Mojito ?",                                          answer: "Le rhum blanc" },
  { id: 187, difficulty: 2, category: "Histoire",    question: "Quel événement a déclenché la Première Guerre Mondiale ?",                                     answer: "L'assassinat de l'archiduc François-Ferdinand à Sarajevo" },
  { id: 188, difficulty: 2, category: "Tech",        question: "Qu'est-ce que le HTML ?",                                                                      answer: "HyperText Markup Language — langage pour les pages web" },
  { id: 189, difficulty: 2, category: "Géographie",  question: "Quelle est la capitale de la Corée du Sud ?",                                                  answer: "Séoul" },
  { id: 190, difficulty: 2, category: "Musique",     question: "Quel est le vrai nom de l'artiste Stromae ?",                                                  answer: "Paul Van Haver" },
  { id: 191, difficulty: 2, category: "Science",     question: "Combien de couleurs composent l'arc-en-ciel ?",                                                answer: "7" },
  { id: 192, difficulty: 2, category: "Sport",       question: "Quelle ville a accueilli les Jeux Olympiques d'été de 2021 ?",                                 answer: "Tokyo" },
  { id: 193, difficulty: 2, category: "Cinéma",      question: "Dans quel film voit-on des dinosaures ressuscités sur une île ?",                              answer: "Jurassic Park" },
  { id: 194, difficulty: 2, category: "Littérature", question: "Qui a écrit \"De la Terre à la Lune\" ?",                                                     answer: "Jules Verne" },
  { id: 195, difficulty: 2, category: "Histoire",    question: "Quel roi d'Angleterre a fondé l'Église anglicane ?",                                           answer: "Henri VIII" },
  { id: 196, difficulty: 2, category: "Géographie",  question: "Quel fleuve traverse Le Caire ?",                                                              answer: "Le Nil" },
  { id: 197, difficulty: 2, category: "Nourriture",  question: "De quelle ville française est originaire la bouillabaisse ?",                                  answer: "Marseille" },
  { id: 198, difficulty: 2, category: "Art",         question: "Quel peintre espagnol est notamment connu pour ses périodes bleue et rose ?",                  answer: "Pablo Picasso" },
  { id: 199, difficulty: 2, category: "Science",     question: "Quel est le métal le plus conducteur d'électricité ?",                                         answer: "L'argent" },
  { id: 200, difficulty: 2, category: "Musique",     question: "Quel groupe de rock a sorti l'album \"Back in Black\" ?",                                     answer: "AC/DC" },

  // ─── DIFFICILE — 3 gorgées ────────────────────────────────────────────────
  { id: 201, difficulty: 3, category: "Géographie",  question: "Quelle est la capitale de la Mongolie ?",                                                       answer: "Oulan-Bator" },
  { id: 202, difficulty: 3, category: "Histoire",    question: "En quelle année est mort Napoléon Bonaparte ?",                                                 answer: "1821" },
  { id: 203, difficulty: 3, category: "Art",         question: "Qui a peint \"La Nuit étoilée\" ?",                                                           answer: "Vincent van Gogh" },
  { id: 204, difficulty: 3, category: "Science",     question: "Quel est l'élément chimique de symbole \"Au\" ?",                                              answer: "L'or" },
  { id: 205, difficulty: 3, category: "Géographie",  question: "Quelle est la plus longue rivière d'Afrique ?",                                                answer: "Le Nil" },
  { id: 206, difficulty: 3, category: "Littérature", question: "Qui a écrit \"À la recherche du temps perdu\" ?",                                             answer: "Marcel Proust" },
  { id: 207, difficulty: 3, category: "Histoire",    question: "En quelle année le Mur de Berlin est-il tombé ?",                                              answer: "1989" },
  { id: 208, difficulty: 3, category: "Sport",       question: "Quel pays a remporté le plus de Coupes du monde de football ? Combien de fois ?",              answer: "Le Brésil — 5 fois" },
  { id: 209, difficulty: 3, category: "Géographie",  question: "Quelle est la capitale des Philippines ?",                                                     answer: "Manille" },
  { id: 210, difficulty: 3, category: "Histoire",    question: "Qui a inventé la dynamite ?",                                                                   answer: "Alfred Nobel" },
  { id: 211, difficulty: 3, category: "Histoire",    question: "Quel est le nom du premier satellite artificiel lancé dans l'espace ?",                        answer: "Spoutnik" },
  { id: 212, difficulty: 3, category: "Littérature", question: "Dans quel roman trouve-t-on le personnage de Holden Caulfield ?",                              answer: "L'Attrape-cœurs (J.D. Salinger)" },
  { id: 213, difficulty: 3, category: "Musique",     question: "Combien de symphonies Beethoven a-t-il composées ?",                                           answer: "9" },
  { id: 214, difficulty: 3, category: "Géographie",  question: "Quel est le pays le plus petit du monde ?",                                                    answer: "Le Vatican" },
  { id: 215, difficulty: 3, category: "Histoire",    question: "En quelle année la Joconde a-t-elle été volée au Louvre ?",                                   answer: "1911" },
  { id: 216, difficulty: 3, category: "Science",     question: "Quel est le symbole chimique du mercure ?",                                                    answer: "Hg" },
  { id: 217, difficulty: 3, category: "Art",         question: "Qui a peint le plafond de la Chapelle Sixtine ?",                                              answer: "Michel-Ange" },
  { id: 218, difficulty: 3, category: "Géographie",  question: "Quelle est la capitale de la Nouvelle-Zélande ?",                                             answer: "Wellington" },
  { id: 219, difficulty: 3, category: "Littérature", question: "Qui est l'auteur de \"Don Quichotte\" ?",                                                     answer: "Miguel de Cervantes" },
  { id: 220, difficulty: 3, category: "Histoire",    question: "En quelle année la Tour Eiffel a-t-elle été inaugurée ?",                                     answer: "1889" },
  { id: 221, difficulty: 3, category: "Science",     question: "Quelle est la vitesse de la lumière (en km/s, arrondie) ?",                                   answer: "300 000 km/s" },
  { id: 222, difficulty: 3, category: "Nourriture",  question: "Quel champignon est le plus cher au monde au kilo ?",                                          answer: "La truffe blanche d'Alba" },
  { id: 223, difficulty: 3, category: "Musique",     question: "Quel groupe a vendu le plus de disques dans l'histoire de la musique ?",                      answer: "Les Beatles" },
  { id: 224, difficulty: 3, category: "Géographie",  question: "Quel est le désert le plus froid du monde ?",                                                  answer: "L'Antarctique" },
  { id: 225, difficulty: 3, category: "Histoire",    question: "En quelle année la République populaire de Chine a-t-elle été fondée ?",                      answer: "1949" },
  { id: 226, difficulty: 3, category: "Géographie",  question: "Quelle est la capitale du Bhoutan ?",                                                          answer: "Thimphou" },
  { id: 227, difficulty: 3, category: "Science",     question: "Quel est le nombre d'Avogadro (ordre de grandeur) ?",                                         answer: "6,022 × 10²³ mol⁻¹" },
  { id: 228, difficulty: 3, category: "Littérature", question: "Quel est le vrai prénom de l'auteur George Orwell ?",                                         answer: "Eric Arthur Blair" },
  { id: 229, difficulty: 3, category: "Art",         question: "En quelle année Michel-Ange a-t-il terminé le plafond de la Chapelle Sixtine ?",              answer: "1512" },
  { id: 230, difficulty: 3, category: "Géographie",  question: "Quel est le point culminant d'Afrique ?",                                                     answer: "Le Kilimandjaro (5 895 m)" },
  { id: 231, difficulty: 3, category: "Histoire",    question: "Qui était le Premier ministre britannique pendant la Seconde Guerre Mondiale ?",               answer: "Winston Churchill" },
  { id: 232, difficulty: 3, category: "Science",     question: "Quelle loi stipule que la pression d'un gaz est inversement proportionnelle à son volume ?",  answer: "La loi de Boyle-Mariotte" },
  { id: 233, difficulty: 3, category: "Musique",     question: "Quel est le nom de la flûte traditionnelle des Andes ?",                                      answer: "La quena" },
  { id: 234, difficulty: 3, category: "Littérature", question: "Dans quel roman de Kafka un homme se transforme-t-il en insecte ?",                           answer: "La Métamorphose" },
  { id: 235, difficulty: 3, category: "Cinéma",      question: "Qui a réalisé le film \"8½\" (Huit et demi) ?",                                               answer: "Federico Fellini" },
  { id: 236, difficulty: 3, category: "Géographie",  question: "Quel est le plus grand lac d'Amérique du Sud ?",                                              answer: "Le lac Titicaca" },
  { id: 237, difficulty: 3, category: "Histoire",    question: "En quelle année fut fondée la ville de Rome, selon la tradition ?",                            answer: "753 avant J.-C." },
  { id: 238, difficulty: 3, category: "Science",     question: "Quelle est la particule subatomique portant une charge positive ?",                            answer: "Le proton" },
  { id: 239, difficulty: 3, category: "Sport",       question: "En quelle année le Tour de France cycliste a-t-il été créé ?",                                answer: "1903" },
  { id: 240, difficulty: 3, category: "Musique",     question: "Quel pianiste polonais est connu pour ses nocturnes ?",                                        answer: "Frédéric Chopin" },
  { id: 241, difficulty: 3, category: "Littérature", question: "Qui a écrit \"L'Odyssée\" et \"L'Iliade\" ?",                                                answer: "Homère" },
  { id: 242, difficulty: 3, category: "Géographie",  question: "Quel est le nom du plus haut plateau du monde, surnommé \"le toit du monde\" ?",              answer: "Le plateau tibétain" },
  { id: 243, difficulty: 3, category: "Histoire",    question: "Qui était le dernier pharaon d'Égypte d'origine macédonienne ?",                              answer: "Cléopâtre VII" },
  { id: 244, difficulty: 3, category: "Cinéma",      question: "Quel film d'Ingmar Bergman montre un chevalier jouant aux échecs contre la Mort ?",           answer: "Le Septième Sceau" },
  { id: 245, difficulty: 3, category: "Science",     question: "Quel est le nom du processus par lequel une cellule se divise en deux cellules filles identiques ?", answer: "La mitose" },
  { id: 246, difficulty: 3, category: "Art",         question: "Quel est le nom de la célèbre sculpture de Rodin représentant deux amants ?",                 answer: "Le Baiser" },
  { id: 247, difficulty: 3, category: "Musique",     question: "En quelle année Beethoven est-il né ?",                                                        answer: "1770" },
  { id: 248, difficulty: 3, category: "Littérature", question: "Quel auteur irlandais a écrit \"Ulysse\" ?",                                                  answer: "James Joyce" },
  { id: 249, difficulty: 3, category: "Histoire",    question: "Quel est le nom du traité qui a mis fin à la Première Guerre Mondiale ?",                     answer: "Le Traité de Versailles (1919)" },
  { id: 250, difficulty: 3, category: "Cinéma",      question: "Qui a réalisé \"Apocalypse Now\" ?",                                                          answer: "Francis Ford Coppola" },
  { id: 251, difficulty: 3, category: "Géographie",  question: "Quelle mer se trouve entre l'Italie et la Croatie ?",                                         answer: "La mer Adriatique" },
  { id: 252, difficulty: 3, category: "Histoire",    question: "Quel philosophe grec a bu la ciguë ?",                                                         answer: "Socrate" },
  { id: 253, difficulty: 3, category: "Art",         question: "Qui a peint \"La Persistance de la mémoire\" (les montres molles) ?",                        answer: "Salvador Dalí" },
  { id: 254, difficulty: 3, category: "Musique",     question: "Quel est le vrai nom de l'artiste Prince ?",                                                   answer: "Prince Rogers Nelson" },
  { id: 255, difficulty: 3, category: "Littérature", question: "Qui a écrit \"Le Procès\" ?",                                                                 answer: "Franz Kafka" },
  { id: 256, difficulty: 3, category: "Cinéma",      question: "Dans quelle ville se déroule principalement l'action de \"Blade Runner\" ?",                  answer: "Los Angeles (futuriste, 2019)" },
  { id: 257, difficulty: 3, category: "Histoire",    question: "En quelle année Jules César a-t-il été assassiné ?",                                          answer: "44 avant J.-C." },
  { id: 258, difficulty: 3, category: "Science",     question: "Quel est le nom donné aux cellules qui transmettent les signaux nerveux ?",                   answer: "Les neurones" },
  { id: 259, difficulty: 3, category: "Art",         question: "Quel architecte a conçu la Sagrada Família à Barcelone ?",                                    answer: "Antoni Gaudí" },
  { id: 260, difficulty: 3, category: "Sport",       question: "Quel est le nom du trophée remis au vainqueur du championnat de NBA ?",                       answer: "Le trophée Larry O'Brien" },
  { id: 261, difficulty: 3, category: "Musique",     question: "Quel est le nom du procédé d'enregistrement sonore inventé par Edison ?",                     answer: "Le phonographe" },
  { id: 262, difficulty: 3, category: "Littérature", question: "Quel est le personnage principal du roman de Stendhal \"Le Rouge et le Noir\" ?",             answer: "Julien Sorel" },
  { id: 263, difficulty: 3, category: "Géographie",  question: "Quelle est la capitale de l'Éthiopie ?",                                                      answer: "Addis-Abeba" },
  { id: 264, difficulty: 3, category: "Cinéma",      question: "En quelle année le film \"Casablanca\" est-il sorti ?",                                       answer: "1942" },
  { id: 265, difficulty: 3, category: "Science",     question: "Quelle est la formule chimique de l'acide sulfurique ?",                                      answer: "H₂SO₄" },
  { id: 266, difficulty: 3, category: "Art",         question: "Quel peintre hollandais du XVIIe siècle est célèbre pour \"La Jeune Fille à la perle\" ?",  answer: "Johannes Vermeer" },
  { id: 267, difficulty: 3, category: "Musique",     question: "Quel est le nom de la technique de composition où plusieurs voix indépendantes se combinent ?", answer: "Le contrepoint" },
  { id: 268, difficulty: 3, category: "Géographie",  question: "Quelle est la plus grande forêt tropicale du monde ?",                                         answer: "La forêt amazonienne" },
  { id: 269, difficulty: 3, category: "Sport",       question: "En quelle année les femmes ont-elles pu participer aux Jeux Olympiques pour la première fois ?", answer: "1900 (Paris)" },
  { id: 270, difficulty: 3, category: "Histoire",    question: "Quel sultan ottoman a conquis Constantinople en 1453 ?",                                       answer: "Mehmed II (Mehmed le Conquérant)" },
  { id: 271, difficulty: 3, category: "Cinéma",      question: "Quel film d'Akira Kurosawa a inspiré George Lucas pour \"Star Wars\" ?",                     answer: "La Forteresse cachée (1958)" },
  { id: 272, difficulty: 3, category: "Science",     question: "Quel est le nom de la théorie qui explique la dérive des continents ?",                       answer: "La tectonique des plaques" },
  { id: 273, difficulty: 3, category: "Art",         question: "En quelle année Picasso a-t-il peint \"Guernica\" ?",                                         answer: "1937" },
  { id: 274, difficulty: 3, category: "Géographie",  question: "Quel est le nom du canal qui relie la mer Rouge à la Méditerranée ?",                        answer: "Le canal de Suez" },
  { id: 275, difficulty: 3, category: "Littérature", question: "Quel auteur a écrit \"Les Fleurs du mal\" ?",                                                 answer: "Charles Baudelaire" },
  { id: 276, difficulty: 3, category: "Histoire",    question: "En quelle année la Déclaration universelle des droits de l'homme a-t-elle été adoptée ?",    answer: "1948" },
  { id: 277, difficulty: 3, category: "Science",     question: "Quelle particule n'a pas de masse et voyage à la vitesse de la lumière ?",                   answer: "Le photon" },
  { id: 278, difficulty: 3, category: "Cinéma",      question: "Quel film de David Lynch raconte l'histoire d'un homme atteint de déformations physiques au XIXe siècle ?", answer: "Elephant Man (1980)" },
  { id: 279, difficulty: 3, category: "Géographie",  question: "Quel détroit sépare le continent américain du continent asiatique ?",                        answer: "Le détroit de Béring" },
  { id: 280, difficulty: 3, category: "Art",         question: "Qui a créé la sculpture \"La Pietà\" exposée au Vatican ?",                                   answer: "Michel-Ange" },
  { id: 281, difficulty: 3, category: "Musique",     question: "Quelle compositrice française du XXe siècle fut la première femme à remporter le Prix de Rome ?", answer: "Lili Boulanger" },
  { id: 282, difficulty: 3, category: "Histoire",    question: "Quelle reine d'Angleterre a régné le plus longtemps ?",                                       answer: "Élisabeth II (70 ans)" },
  { id: 283, difficulty: 3, category: "Science",     question: "Quelle est la durée approximative d'une révolution de la Terre autour du Soleil ?",          answer: "365,25 jours" },
  { id: 284, difficulty: 3, category: "Géographie",  question: "Quel pays possède le plus de volcans actifs du monde ?",                                      answer: "L'Indonésie" },
  { id: 285, difficulty: 3, category: "Cinéma",      question: "Qui a joué le rôle d'Hannibal Lecter dans \"Le Silence des agneaux\" ?",                     answer: "Anthony Hopkins" },
  { id: 286, difficulty: 3, category: "Littérature", question: "Dans \"Les Frères Karamazov\", quel est le prénom du père assassiné ?",                      answer: "Fiodor Karamazov" },
  { id: 287, difficulty: 3, category: "Sport",       question: "En quelle année a eu lieu la première édition moderne des Jeux Olympiques ?",                 answer: "1896 (Athènes)" },
  { id: 288, difficulty: 3, category: "Histoire",    question: "Quel philosophe a écrit \"La République\" ?",                                                 answer: "Platon" },
  { id: 289, difficulty: 3, category: "Science",     question: "Quel est le nom de la loi qui relie tension, intensité et résistance en électricité ?",      answer: "La loi d'Ohm" },
  { id: 290, difficulty: 3, category: "Art",         question: "Quel peintre néerlandais a coupé son oreille ?",                                              answer: "Vincent van Gogh" },
  { id: 291, difficulty: 3, category: "Géographie",  question: "Quelle est la capitale du Kazakhstan ?",                                                      answer: "Astana" },
  { id: 292, difficulty: 3, category: "Musique",     question: "En quelle décennie la musique disco a-t-elle atteint son apogée ?",                          answer: "Les années 1970" },
  { id: 293, difficulty: 3, category: "Littérature", question: "Qui a écrit \"Candide\" ?",                                                                  answer: "Voltaire" },
  { id: 294, difficulty: 3, category: "Histoire",    question: "Quel peuple ancien a construit le Machu Picchu ?",                                            answer: "Les Incas" },
  { id: 295, difficulty: 3, category: "Science",     question: "Quel est le symbole chimique du potassium ?",                                                 answer: "K" },
  { id: 296, difficulty: 3, category: "Cinéma",      question: "Dans quel pays a été tourné le film \"Lawrence d'Arabie\" (1962) ?",                         answer: "En Jordanie (et Espagne)" },
  { id: 297, difficulty: 3, category: "Sport",       question: "Quel pays a remporté le plus de médailles aux Jeux Paralympiques de tous les temps ?",       answer: "Les États-Unis" },
  { id: 298, difficulty: 3, category: "Art",         question: "Quel est le nom du style artistique caractérisé par des formes géométriques fragmentées ?",  answer: "Le cubisme" },
  { id: 299, difficulty: 3, category: "Géographie",  question: "Quel est le nom du plus grand cratère météoritique visible à la surface de la Terre ?",     answer: "Le cratère de Vredefort (Afrique du Sud)" },
  { id: 300, difficulty: 3, category: "Histoire",    question: "En quelle année la Grèce a-t-elle intégré l'Union Européenne ?",                             answer: "1981" },
];
